import { useState } from 'react';
import { CheckCircle2, Send, X } from 'lucide-react';
import { sendToGoogleSheet } from '../services/googleSheet';

const productOptions = ['IMSAFE - Kavasam Safety Solutions Spray Fire Extinguisher', 'Spray Fire Extinguisher - Pack of 2', 'Spray Fire Extinguisher - Pack of 3', 'Fire Blanket', 'Temperature Clips', 'Fire Thread', 'Throw Fire Extinguisher + Fire Blanket', 'Smart Kill Fire Kit', '5-in-1 Emergency Toolkit'];
const initial = { name: '', phone: '', email: '', address: '', product: productOptions[0] };

export default function OrderForm({ visitor, onClose }) {
  const [form, setForm] = useState({ ...initial, name: visitor?.name || '', phone: visitor?.phone || '', email: visitor?.email || '' });
  const [error, setError] = useState('');
  const [submitted, setSubmitted] = useState(false);
  const [loading, setLoading] = useState(false);
  const update = (event) => { setForm((current) => ({ ...current, [event.target.name]: event.target.value })); setError(''); };
  async function submit(event) { event.preventDefault(); if (Object.values(form).some((value) => !value.trim()) || !/^\d{10}$/.test(form.phone.replace(/\D/g, ''))) { setError('Please complete every field with a valid 10-digit phone number.'); return; } setLoading(true); await sendToGoogleSheet({ type: 'order', ...form, phone: form.phone.replace(/\D/g, '') }); setLoading(false); setSubmitted(true); }
  return <div className="modal-backdrop" role="presentation"><div className="order-modal" role="dialog" aria-modal="true" aria-labelledby="order-title"><button className="close-button" onClick={onClose} aria-label="Close order form"><X /></button>{submitted ? <div className="success-state"><CheckCircle2 size={54} /><p className="eyebrow">ORDER RECEIVED</p><h2>We’ll take it<br /><em>from here.</em></h2><p>Thanks, {form.name.split(' ')[0]}. Our safety specialist will be in touch shortly to confirm your order.</p><button className="button button-dark" onClick={onClose}>Back to IMSAFE - Kavasam Safety Solutions</button></div> : <><div className="modal-intro"><p className="eyebrow">GET PROTECTED</p><h2 id="order-title">Make your space<br /><em>IMSAFE - Kavasam Safety Solutions.</em></h2><p>Share your details and we’ll help you choose the right protection.</p></div><form onSubmit={submit} className="order-form" noValidate><div className="form-row"><label>Full name<input name="name" value={form.name} onChange={update} placeholder="Your name" /></label><label>Phone number<input name="phone" value={form.phone} onChange={update} placeholder="10-digit number" inputMode="numeric" /></label></div><div className="form-row"><label>Email ID<input name="email" value={form.email} onChange={update} placeholder="you@company.com" type="email" /></label><label>Product<select name="product" value={form.product} onChange={update}>{productOptions.map((product) => <option key={product}>{product}</option>)}</select></label></div><label>Delivery address<textarea name="address" value={form.address} onChange={update} placeholder="House / office address, city and PIN code" rows="3" /></label>{error && <p className="form-error">{error}</p>}<button className="button button-red order-submit" disabled={loading}>{loading ? 'Sending order...' : <>Submit order <Send size={16} /></>}</button></form></>}</div></div>;
}
