import { useState } from 'react';
import { ArrowRight, Check, Flame, ShieldCheck } from 'lucide-react';
import { sendToGoogleSheet } from './services/googleSheet';
const initialForm = { name: '', phone: '', email: '' };
export default function Login({ onEnter }) {
	const [form, setForm] = useState(initialForm); const [error, setError] = useState(''); const [isSubmitting, setIsSubmitting] = useState(false);
	function updateField(event) { setForm((current) => ({ ...current, [event.target.name]: event.target.value })); setError(''); }
	async function handleSubmit(event) { event.preventDefault(); if (!form.name.trim() || !/^\d{10}$/.test(form.phone.replace(/\D/g, '')) || !/^\S+@\S+\.\S+$/.test(form.email)) { setError('Please enter your name, a valid 10-digit phone number, and a valid email.'); return; } setIsSubmitting(true); const result = await sendToGoogleSheet({ type: 'login', ...form, phone: form.phone.replace(/\D/g, '') }); setIsSubmitting(false); if (!result.ok) { setError(result.error || 'Your details could not be saved. Please try again.'); return; } onEnter(form); }
	return <main className="entry-page"><section className="entry-visual"><div className="entry-grid" /><div className="entry-brand"><span className="brand-mark"><Flame size={18} /></span> IMSAFE - Kavasam Safety Solutions</div><div className="entry-copy"><p className="eyebrow light"><span /> LIFE MATTERS</p><h1>Protection starts<br /><em>before</em> the flame.</h1><p className="entry-lede">Purpose-built fire safety products for the moments that matter most.</p><div className="entry-points"><span><ShieldCheck size={17} /> Certified protection</span><span><Check size={17} /> Safe for home & business</span></div></div><div className="entry-orbit" /><div className="entry-note">01 / SAFETY FIRST</div></section><section className="entry-form-wrap"><div className="entry-form-inner"><div className="mobile-brand"><span className="brand-mark"><Flame size={16} /></span> IMSAFE - Kavasam Safety Solutions</div><p className="eyebrow">WELCOME TO IMSAFE - Kavasam Safety Solutions</p><h2>Let’s make your space<br /><span>safer.</span></h2><p className="form-intro">Tell us a little about yourself to explore our fire safety range.</p><form onSubmit={handleSubmit} noValidate><label>Your name<input name="name" value={form.name} onChange={updateField} placeholder="Enter your full name" autoComplete="name" /></label><label>Phone number<div className="phone-field"><span>+91</span><input name="phone" value={form.phone} onChange={updateField} placeholder="10-digit number" inputMode="numeric" autoComplete="tel" /></div></label><label>Email address<input name="email" value={form.email} onChange={updateField} placeholder="you@company.com" type="email" autoComplete="email" /></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="button button-dark submit-button" disabled={isSubmitting}>{isSubmitting ? 'Opening your safety guide...' : <>Enter the safety guide <ArrowRight size={18} /></>}</button></form><p className="privacy-note"><ShieldCheck size={14} /> Your details are used only to help with your enquiry.</p></div></section></main>;
}
